language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -U pip wheel
  - pip install setuptools==24.0.3
  - pip install -r requirements.txt
  - python setup.py -q install
# Run the tests and then some commands to at least give the modules
# a workout.
script:
  - python setup.py test
  - pywind decc_extract
  - pywind ofgem_certificate_search --period 201601
#  - pywind bm_system_prices --export xml
  - pywind roc_prices --export csv

